name: Jekyll site CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: false

    - name: Install dependencies
      run: |
        bundle lock --add-platform x86_64-linux
        bundle install --path vendor/bundle --jobs 4 --retry 3

    - name: Build site
      env:
        JEKYLL_ENV: production
        JEKYLL_THEME: null
      run: |
        bundle exec jekyll build --verbose --trace

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: site
        path: _site/