name: Jekyll site CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true

    - name: Install dependencies
      run: |
        bundle install --path vendor/bundle

    - name: Build site
      run: |
        bundle exec jekyll build --verbose --trace

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: site
        path: _site/ 